Repository amattas/hass-dmp, pull requests merged in 2025-01, with the labels that each got.

#23 Fix constants
  custom_components/dmp/alarm_control_panel.py
  hacs.json
Labels: enhancement

#27 Added Motion Detection Support
  custom_components/dmp/binary_sensor.py
  custom_components/dmp/sensor.py
Labels: enhancement

#28 Feature/ha warnings rebase
  custom_components/dmp/__init__.py
  custom_components/dmp/alarm_control_panel.py
Labels: bug, enhancement

#30 Fixed inconsistent icons for motion sensor
  custom_components/dmp/binary_sensor.py
  custom_components/dmp/sensor.py
Labels: bug
